apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-app-hpa  # Называем HPA "web-app-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app  # Указываем, что масштабируем Deployment "web-app"
  minReplicas: 2  # Минимальное количество подов (ночью)
  maxReplicas: 4  # Максимальное количество подов (днем)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Масштабируем, если использование CPU превышает 50%